# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Use case: authenticate a user and issue a token pair."""

from dataclasses import dataclass

from app.application.auth.dto import TokenPair
from app.application.shared.interfaces import PasswordHasher, TokenService, UnitOfWork
from app.domain.auth.exceptions import InvalidCredentialsError
from app.domain.shared.exceptions import ValidationError
from app.domain.users.value_objects import Email


@dataclass(frozen=True, slots=True)
class LoginCommand:
    email: str
    password: str


class LoginHandler:
    def __init__(
        self,
        uow: UnitOfWork,
        password_hasher: PasswordHasher,
        token_service: TokenService,
    ) -> None:
        self._uow = uow
        self._hasher = password_hasher
        self._tokens = token_service

    async def execute(self, command: LoginCommand) -> TokenPair:
        try:
            email = Email(command.email)
        except ValidationError:
            # Don't leak whether the address is even well-formed.
            raise InvalidCredentialsError from None

        user = await self._uow.users.get_by_email(email)
        if user is None or not user.is_active:
            raise InvalidCredentialsError
        if not self._hasher.verify(command.password, user.hashed_password.value):
            raise InvalidCredentialsError

        subject = str(user.id)
        return TokenPair(
            access_token=self._tokens.create_access_token(subject),
            refresh_token=self._tokens.create_refresh_token(subject),
        )
