# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Use case: log out by revoking the presented refresh token's family."""

from dataclasses import dataclass

from app.application.shared.interfaces import Clock, TokenService, UnitOfWork
from app.domain.auth.exceptions import InvalidTokenError


@dataclass(frozen=True, slots=True)
class LogoutCommand:
    refresh_token: str


class LogoutHandler:
    def __init__(
        self, uow: UnitOfWork, token_service: TokenService, clock: Clock
    ) -> None:
        self._uow = uow
        self._tokens = token_service
        self._clock = clock

    async def execute(self, command: LogoutCommand) -> None:
        payload = self._tokens.decode(command.refresh_token)
        if payload.token_type != "refresh":
            raise InvalidTokenError

        record = await self._uow.refresh_tokens.get_by_jti(payload.token_id)
        if record is None:
            # Nothing to revoke; treat as already logged out (idempotent).
            return
        await self._uow.refresh_tokens.revoke_family(
            record.family_id, self._clock.now()
        )
        await self._uow.commit()
