# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Use case: exchange a refresh token for a new token pair."""

from dataclasses import dataclass

from app.application.auth.dto import TokenPair
from app.application.shared.interfaces import TokenService, UnitOfWork
from app.domain.auth.exceptions import InvalidTokenError
from app.domain.shared.exceptions import ValidationError
from app.domain.users.value_objects import UserId


@dataclass(frozen=True, slots=True)
class RefreshTokenCommand:
    refresh_token: str


class RefreshTokenHandler:
    def __init__(self, uow: UnitOfWork, token_service: TokenService) -> None:
        self._uow = uow
        self._tokens = token_service

    async def execute(self, command: RefreshTokenCommand) -> TokenPair:
        payload = self._tokens.decode(command.refresh_token)
        if payload.token_type != "refresh":
            raise InvalidTokenError

        try:
            user_id = UserId.from_str(payload.subject)
        except ValidationError:
            raise InvalidTokenError from None

        user = await self._uow.users.get_by_id(user_id)
        if user is None or not user.is_active:
            raise InvalidTokenError

        subject = str(user.id)
        return TokenPair(
            access_token=self._tokens.create_access_token(subject),
            refresh_token=self._tokens.create_refresh_token(subject),
        )
