# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""In-process domain-event dispatcher.

The lean default: handlers run in the same process, after the commit that
produced the events. Delivery is therefore at-most-once — if the process dies
between commit and dispatch, the event is lost. When that guarantee is not
enough (emails, webhooks, cross-service messaging), upgrade to the
transactional outbox described in this package's README; the port stays the
same, so call sites do not change.
"""

from collections.abc import Awaitable, Callable, Sequence

import structlog

from app.domain.shared.events import DomainEvent
from app.domain.users.events import UserRegistered

logger = structlog.get_logger()


class InProcessEventDispatcher:
    """Routes events to handlers registered per concrete event type."""

    def __init__(self) -> None:
        self._handlers: list[Callable[[DomainEvent], Awaitable[None]]] = []

    def register[E: DomainEvent](
        self,
        event_type: type[E],
        handler: Callable[[E], Awaitable[None]],
    ) -> None:
        # The closure narrows DomainEvent to E via isinstance, keeping the
        # public registry fully typed without casts.
        async def dispatch_if_match(event: DomainEvent) -> None:
            if isinstance(event, event_type):
                await handler(event)

        self._handlers.append(dispatch_if_match)

    async def dispatch(self, events: Sequence[DomainEvent]) -> None:
        for event in events:
            logger.info("domain_event.dispatched", event_type=type(event).__name__)
            for handler in self._handlers:
                await handler(event)


async def log_user_registered(event: UserRegistered) -> None:
    """Default demo handler: replace with email verification, analytics, etc."""
    logger.info(
        "user.registered",
        user_id=str(event.user_id),
        email=event.email,
    )
