# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Redis-backed fixed-window rate limiter.

INCR + EXPIRE per key: the first hit in a window creates the counter with a
TTL; once the counter exceeds the limit, callers are told how long to wait.
Fixed windows are a deliberate simplicity trade-off for a starter — swap in a
sliding-window or token-bucket implementation behind the same port if your
traffic profile needs it.
"""

from redis.asyncio import Redis

from app.application.shared.interfaces import RateLimitDecision

_KEY_PREFIX = "ratelimit"


def create_redis_client(url: str) -> Redis:
    """Builds the shared async Redis client (one per process, APP scope)."""
    return Redis.from_url(url)


class RedisRateLimiter:
    """Implements the RateLimiter port on redis.asyncio."""

    def __init__(self, redis: Redis) -> None:
        self._redis = redis

    async def check(
        self, key: str, limit: int, window_seconds: int
    ) -> RateLimitDecision:
        redis_key = f"{_KEY_PREFIX}:{key}"
        count = int(await self._redis.incr(redis_key))
        if count == 1:
            await self._redis.expire(redis_key, window_seconds)
        if count > limit:
            ttl = int(await self._redis.ttl(redis_key))
            return RateLimitDecision(allowed=False, retry_after_seconds=max(ttl, 1))
        return RateLimitDecision(allowed=True, retry_after_seconds=0)
