# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""System clock implementation of the Clock port."""

from datetime import UTC, datetime


class SystemClock:
    """Returns timezone-aware UTC timestamps."""

    def now(self) -> datetime:
        return datetime.now(UTC)
