# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Auth DTOs."""

from dataclasses import dataclass
from typing import Literal


@dataclass(frozen=True, slots=True)
class TokenPair:
    access_token: str
    refresh_token: str
    token_type: Literal["bearer"] = "bearer"
