# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Composition root: assembles the Dishka container.

This is the one place that knows about every layer at once. Everything else
depends only on abstractions and is wired together here.
"""

from dishka import AsyncContainer, make_async_container
from dishka.integrations.fastapi import FastapiProvider

from app.core.config import Settings
from app.ioc.providers.config import ConfigProvider
from app.ioc.providers.database import DatabaseProvider
from app.ioc.providers.security import SecurityProvider
from app.ioc.providers.use_cases import UseCasesProvider


def create_container(settings: Settings) -> AsyncContainer:
    return make_async_container(
        ConfigProvider(),
        DatabaseProvider(),
        SecurityProvider(),
        UseCasesProvider(),
        FastapiProvider(),
        context={Settings: settings},
    )
