# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Shared application DTOs."""

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Page[T]:
    """A cursor-paginated slice of results.

    ``next_cursor`` is an opaque token the client passes back to fetch the next
    page; ``None`` means there are no further results. We use keyset (cursor)
    pagination instead of OFFSET so query performance stays constant on large
    tables.
    """

    items: list[T]
    next_cursor: str | None
