# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Shared test fixtures.

Integration tests run the full app (routers, DI container, use cases, ORM)
against an in-memory SQLite database, so they exercise real wiring without
needing Postgres. Each test gets a fresh app + schema for isolation.
"""

from collections.abc import AsyncIterator, Iterator

import pytest
from dishka import AsyncContainer
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient
from pydantic import SecretStr
from sqlalchemy.ext.asyncio import AsyncEngine

from app.core.config import (
    AppSettings,
    DatabaseSettings,
    Environment,
    JwtSettings,
    Settings,
    get_settings,
)
from app.infrastructure.database.models.base import Base
from app.main import create_app


@pytest.fixture(autouse=True)
def reset_settings_cache() -> Iterator[None]:
    """Keep ``get_settings()`` from leaking cached state between tests."""
    get_settings.cache_clear()
    yield
    get_settings.cache_clear()


def _test_settings() -> Settings:
    return Settings(
        environment=Environment.TEST,
        # debug=False keeps Starlette's debug tracebacks out of the way so the
        # catch-all problem+json handler is exercised exactly as in production.
        app=AppSettings(name="test", debug=False),
        database=DatabaseSettings(url=SecretStr("sqlite+aiosqlite:///:memory:")),
        jwt=JwtSettings(
            secret=SecretStr("test-secret-key-please-change-0123456789")  # >=32 bytes
        ),
    )


@pytest.fixture
async def app() -> AsyncIterator[FastAPI]:
    application = create_app(_test_settings())
    container: AsyncContainer = application.state.dishka_container
    engine = await container.get(AsyncEngine)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield application
    await container.close()


@pytest.fixture
async def client(app: FastAPI) -> AsyncIterator[AsyncClient]:
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as http_client:
        yield http_client


@pytest.fixture
async def auth_headers(client: AsyncClient) -> dict[str, str]:
    """Registers a user and returns a valid bearer-token header."""
    credentials = {"email": "fixture-user@example.com", "password": "supersecret"}
    await client.post("/api/v1/auth/register", json=credentials)
    response = await client.post("/api/v1/auth/login", json=credentials)
    return {"Authorization": f"Bearer {response.json()['access_token']}"}
