# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Hand-rolled builders for domain objects.

A plain function beats a factory library at this scale: one aggregate, five
fields. Override only what the test cares about.
"""

from datetime import UTC, datetime

from app.domain.users.entities import User
from app.domain.users.value_objects import Email, HashedPassword, UserId

DEFAULT_CREATED_AT = datetime(2026, 1, 1, tzinfo=UTC)


def make_user(
    *,
    email: str = "user@example.com",
    password: str = "supersecret",
    is_active: bool = True,
    created_at: datetime = DEFAULT_CREATED_AT,
) -> User:
    """Builds a User whose password matches StubPasswordHasher's scheme."""
    user = User.create(
        user_id=UserId.new(),
        email=Email(email),
        hashed_password=HashedPassword(f"stub${password}"),
        created_at=created_at,
    )
    user.pull_events()  # tests opt in to events explicitly
    if not is_active:
        user.deactivate()
    return user
