# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Rotation, reuse detection, expiry, and logout — pure in-memory."""

from datetime import timedelta

import pytest

from app.application.auth.commands.login import LoginCommand, LoginHandler
from app.application.auth.commands.logout import LogoutCommand, LogoutHandler
from app.application.auth.commands.refresh_token import (
    RefreshTokenCommand,
    RefreshTokenHandler,
)
from app.domain.auth.exceptions import InvalidTokenError, TokenExpiredError
from tests.factories import make_user
from tests.fakes import (
    FakeTokenService,
    FakeUnitOfWork,
    FrozenClock,
    StubPasswordHasher,
)


async def _logged_in(uow: FakeUnitOfWork, tokens: FakeTokenService) -> str:
    await uow.users.add(make_user(email="ref@example.com"))
    pair = await LoginHandler(uow, StubPasswordHasher(), tokens).execute(
        LoginCommand(email="ref@example.com", password="supersecret")
    )
    return pair.refresh_token


async def test_refresh_rotates_within_the_same_family() -> None:
    uow = FakeUnitOfWork()
    clock = FrozenClock()
    tokens = FakeTokenService(clock)
    refresh_token = await _logged_in(uow, tokens)
    handler = RefreshTokenHandler(uow, tokens, clock)

    pair = await handler.execute(RefreshTokenCommand(refresh_token=refresh_token))

    records = list(uow.refresh_tokens.records.values())
    assert len(records) == 2
    revoked = [r for r in records if r.is_revoked]
    live = [r for r in records if not r.is_revoked]
    assert len(revoked) == 1 and len(live) == 1
    assert revoked[0].family_id == live[0].family_id
    assert pair.refresh_token != refresh_token


async def test_replaying_a_rotated_token_revokes_the_family() -> None:
    uow = FakeUnitOfWork()
    clock = FrozenClock()
    tokens = FakeTokenService(clock)
    refresh_token = await _logged_in(uow, tokens)
    handler = RefreshTokenHandler(uow, tokens, clock)

    await handler.execute(RefreshTokenCommand(refresh_token=refresh_token))
    with pytest.raises(InvalidTokenError):
        await handler.execute(RefreshTokenCommand(refresh_token=refresh_token))

    assert all(r.is_revoked for r in uow.refresh_tokens.records.values())


async def test_expired_record_raises_token_expired() -> None:
    uow = FakeUnitOfWork()
    clock = FrozenClock()
    tokens = FakeTokenService(clock)
    refresh_token = await _logged_in(uow, tokens)
    clock.advance(FakeTokenService.refresh_lifetime + timedelta(seconds=1))
    handler = RefreshTokenHandler(uow, tokens, clock)

    with pytest.raises(TokenExpiredError):
        await handler.execute(RefreshTokenCommand(refresh_token=refresh_token))


async def test_access_token_is_rejected_for_refresh() -> None:
    uow = FakeUnitOfWork()
    tokens = FakeTokenService()
    handler = RefreshTokenHandler(uow, tokens, FrozenClock())

    with pytest.raises(InvalidTokenError):
        await handler.execute(
            RefreshTokenCommand(refresh_token=tokens.create_access_token("someone"))
        )


async def test_logout_revokes_family_and_is_idempotent() -> None:
    uow = FakeUnitOfWork()
    clock = FrozenClock()
    tokens = FakeTokenService(clock)
    refresh_token = await _logged_in(uow, tokens)
    handler = LogoutHandler(uow, tokens, clock)

    await handler.execute(LogoutCommand(refresh_token=refresh_token))
    assert all(r.is_revoked for r in uow.refresh_tokens.records.values())

    # Second logout with the same token is a quiet no-op at the family level.
    await handler.execute(LogoutCommand(refresh_token=refresh_token))
