# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""CreateUserHandler unit tests over in-memory fakes — no I/O, no Argon2."""

import pytest

from app.application.users.commands.create_user import (
    CreateUserCommand,
    CreateUserHandler,
)
from app.domain.users.events import UserRegistered
from app.domain.users.exceptions import EmailAlreadyExistsError
from tests.factories import make_user
from tests.fakes import (
    FakeUnitOfWork,
    FrozenClock,
    RecordingEventDispatcher,
    StubPasswordHasher,
)


def _handler(
    uow: FakeUnitOfWork, events: RecordingEventDispatcher
) -> CreateUserHandler:
    return CreateUserHandler(uow, StubPasswordHasher(), FrozenClock(), events)


async def test_creates_user_commits_and_dispatches_event() -> None:
    uow = FakeUnitOfWork()
    events = RecordingEventDispatcher()

    view = await _handler(uow, events).execute(
        CreateUserCommand(email="New@Example.com", password="supersecret")
    )

    assert view.email == "new@example.com"  # normalised by the Email VO
    assert view.is_active
    assert uow.commits == 1
    assert len(uow.users.users) == 1
    assert [type(e) for e in events.dispatched] == [UserRegistered]


async def test_duplicate_email_raises_and_does_not_commit() -> None:
    uow = FakeUnitOfWork()
    events = RecordingEventDispatcher()
    existing = make_user(email="taken@example.com")
    await uow.users.add(existing)

    with pytest.raises(EmailAlreadyExistsError):
        await _handler(uow, events).execute(
            CreateUserCommand(email="taken@example.com", password="supersecret")
        )
    assert uow.commits == 0
    assert events.dispatched == []
