# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""LoginHandler unit tests, including the anti-enumeration branches."""

import pytest

from app.application.auth.commands.login import LoginCommand, LoginHandler
from app.domain.auth.exceptions import InvalidCredentialsError
from tests.factories import make_user
from tests.fakes import FakeTokenService, FakeUnitOfWork, StubPasswordHasher


async def test_login_returns_pair_and_persists_refresh_record() -> None:
    uow = FakeUnitOfWork()
    await uow.users.add(make_user(email="known@example.com"))
    handler = LoginHandler(uow, StubPasswordHasher(), FakeTokenService())

    pair = await handler.execute(
        LoginCommand(email="known@example.com", password="supersecret")
    )

    assert pair.access_token.startswith("access:")
    assert pair.refresh_token.startswith("refresh:")
    assert uow.commits == 1
    assert len(uow.refresh_tokens.records) == 1
    record = next(iter(uow.refresh_tokens.records.values()))
    assert not record.is_revoked


@pytest.mark.parametrize(
    ("email", "password"),
    [
        ("unknown@example.com", "supersecret"),  # unknown account
        ("known@example.com", "wrong-password"),  # wrong password
        ("not-an-email", "supersecret"),  # malformed email → same error
    ],
)
async def test_login_failures_are_indistinguishable(email: str, password: str) -> None:
    uow = FakeUnitOfWork()
    await uow.users.add(make_user(email="known@example.com"))
    handler = LoginHandler(uow, StubPasswordHasher(), FakeTokenService())

    with pytest.raises(InvalidCredentialsError):
        await handler.execute(LoginCommand(email=email, password=password))
    assert uow.refresh_tokens.records == {}


async def test_inactive_user_cannot_login() -> None:
    uow = FakeUnitOfWork()
    await uow.users.add(make_user(email="gone@example.com", is_active=False))
    handler = LoginHandler(uow, StubPasswordHasher(), FakeTokenService())

    with pytest.raises(InvalidCredentialsError):
        await handler.execute(
            LoginCommand(email="gone@example.com", password="supersecret")
        )


async def test_unknown_user_still_pays_hash_cost() -> None:
    """The timing-equalisation branch must actually hash."""
    uow = FakeUnitOfWork()
    hasher = StubPasswordHasher()
    handler = LoginHandler(uow, hasher, FakeTokenService())

    with pytest.raises(InvalidCredentialsError):
        await handler.execute(
            LoginCommand(email="ghost@example.com", password="whatever-1")
        )
    assert hasher.hash_calls == 1
