# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""ChangePasswordHandler unit tests: update path + session revocation."""

import pytest

from app.application.auth.commands.login import LoginCommand, LoginHandler
from app.application.users.commands.change_password import (
    ChangePasswordCommand,
    ChangePasswordHandler,
)
from app.domain.auth.exceptions import InvalidCredentialsError
from app.domain.users.exceptions import UserNotFoundError
from app.domain.users.value_objects import UserId
from tests.factories import make_user
from tests.fakes import (
    FakeTokenService,
    FakeUnitOfWork,
    FrozenClock,
    StubPasswordHasher,
)


async def test_change_password_updates_hash_and_revokes_sessions() -> None:
    uow = FakeUnitOfWork()
    user = make_user(email="cp@example.com")
    await uow.users.add(user)
    # An existing session that must die with the old password:
    await LoginHandler(uow, StubPasswordHasher(), FakeTokenService()).execute(
        LoginCommand(email="cp@example.com", password="supersecret")
    )
    handler = ChangePasswordHandler(uow, StubPasswordHasher(), FrozenClock())

    await handler.execute(
        ChangePasswordCommand(
            user_id=user.id.value,
            current_password="supersecret",
            new_password="another-pass-1",
        )
    )

    stored = await uow.users.get_by_id(user.id)
    assert stored is not None
    assert stored.hashed_password.value == "stub$another-pass-1"
    assert all(r.is_revoked for r in uow.refresh_tokens.records.values())


async def test_wrong_current_password_is_rejected() -> None:
    uow = FakeUnitOfWork()
    user = make_user()
    await uow.users.add(user)
    handler = ChangePasswordHandler(uow, StubPasswordHasher(), FrozenClock())

    with pytest.raises(InvalidCredentialsError):
        await handler.execute(
            ChangePasswordCommand(
                user_id=user.id.value,
                current_password="not-it",
                new_password="whatever-12",
            )
        )
    assert uow.commits == 0


async def test_unknown_user_raises_not_found() -> None:
    handler = ChangePasswordHandler(
        FakeUnitOfWork(), StubPasswordHasher(), FrozenClock()
    )
    with pytest.raises(UserNotFoundError):
        await handler.execute(
            ChangePasswordCommand(
                user_id=UserId.new().value,
                current_password="x" * 8,
                new_password="y" * 8,
            )
        )
