# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Auth API endpoints: public registration, login, and token refresh."""

from dishka.integrations.fastapi import DishkaRoute, FromDishka
from fastapi import APIRouter, status

from app.api.exception_handlers import problem_responses
from app.api.v1.auth.schemas import (
    LoginRequest,
    RefreshRequest,
    RegisterRequest,
    TokenResponse,
)
from app.api.v1.users.schemas import UserResponse
from app.application.auth.commands.login import LoginCommand, LoginHandler
from app.application.auth.commands.refresh_token import (
    RefreshTokenCommand,
    RefreshTokenHandler,
)
from app.application.users.commands.create_user import (
    CreateUserCommand,
    CreateUserHandler,
)

router = APIRouter(prefix="/auth", tags=["auth"], route_class=DishkaRoute)


@router.post(
    "/register",
    status_code=status.HTTP_201_CREATED,
    response_model=UserResponse,
    responses=problem_responses(409),
)
async def register(
    body: RegisterRequest,
    handler: FromDishka[CreateUserHandler],
) -> UserResponse:
    view = await handler.execute(
        CreateUserCommand(email=body.email, password=body.password)
    )
    return UserResponse.model_validate(view)


@router.post("/login", response_model=TokenResponse, responses=problem_responses(401))
async def login(
    body: LoginRequest,
    handler: FromDishka[LoginHandler],
) -> TokenResponse:
    tokens = await handler.execute(
        LoginCommand(email=body.email, password=body.password)
    )
    return TokenResponse(
        access_token=tokens.access_token,
        refresh_token=tokens.refresh_token,
        token_type=tokens.token_type,
    )


@router.post("/refresh", response_model=TokenResponse, responses=problem_responses(401))
async def refresh(
    body: RefreshRequest,
    handler: FromDishka[RefreshTokenHandler],
) -> TokenResponse:
    tokens = await handler.execute(
        RefreshTokenCommand(refresh_token=body.refresh_token)
    )
    return TokenResponse(
        access_token=tokens.access_token,
        refresh_token=tokens.refresh_token,
        token_type=tokens.token_type,
    )
