# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Cache-backed infrastructure providers: Redis client and rate limiter."""

from collections.abc import AsyncIterable

from dishka import Provider, Scope, provide
from redis.asyncio import Redis

from app.application.shared.interfaces import RateLimiter
from app.core.config import RedisSettings
from app.infrastructure.cache.rate_limiter import RedisRateLimiter, create_redis_client


class CacheProvider(Provider):
    scope = Scope.APP

    @provide
    async def redis_client(self, settings: RedisSettings) -> AsyncIterable[Redis]:
        client = create_redis_client(settings.url.get_secret_value())
        yield client
        await client.aclose()

    @provide
    def rate_limiter(self, redis: Redis) -> RateLimiter:
        return RedisRateLimiter(redis)
