# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Provides configuration objects to the container.

The concrete ``Settings`` instance is supplied to the container via ``context``
(see ``app/ioc/container.py``) and exposed here with ``from_context``. Sub-models
are derived from it so lower layers depend only on the slice they need.
"""

from dishka import Provider, Scope, from_context, provide

from app.core.config import (
    DatabaseSettings,
    JwtSettings,
    RateLimitSettings,
    RedisSettings,
    Settings,
)


class ConfigProvider(Provider):
    scope = Scope.APP

    settings = from_context(provides=Settings, scope=Scope.APP)

    @provide
    def database_settings(self, settings: Settings) -> DatabaseSettings:
        return settings.database

    @provide
    def jwt_settings(self, settings: Settings) -> JwtSettings:
        return settings.jwt

    @provide
    def redis_settings(self, settings: Settings) -> RedisSettings:
        return settings.redis

    @provide
    def rate_limit_settings(self, settings: Settings) -> RateLimitSettings:
        return settings.rate_limit
