# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Database providers: engine, session factory, session, unit of work, read model.

Scopes:
- ``APP``: the engine and session factory are created once for the process.
- ``REQUEST``: one session per request; the unit of work and read model wrap it,
  so writes and reads in a request share a single transaction.
"""

from collections.abc import AsyncIterable

from dishka import Provider, Scope, provide
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, async_sessionmaker

from app.application.shared.interfaces import UnitOfWork
from app.application.users.interfaces import UserQueryService
from app.core.config import DatabaseSettings
from app.infrastructure.database.repositories.user_query_service import (
    SqlAlchemyUserQueryService,
)
from app.infrastructure.database.session import (
    create_engine,
    create_session_factory,
)
from app.infrastructure.database.unit_of_work import SqlAlchemyUnitOfWork


class DatabaseProvider(Provider):
    @provide(scope=Scope.APP)
    async def engine(self, settings: DatabaseSettings) -> AsyncIterable[AsyncEngine]:
        engine = create_engine(settings)
        yield engine
        await engine.dispose()

    @provide(scope=Scope.APP)
    def session_factory(self, engine: AsyncEngine) -> async_sessionmaker[AsyncSession]:
        return create_session_factory(engine)

    @provide(scope=Scope.REQUEST)
    async def session(
        self, factory: async_sessionmaker[AsyncSession]
    ) -> AsyncIterable[AsyncSession]:
        async with factory() as session:
            yield session

    @provide(scope=Scope.REQUEST)
    def unit_of_work(self, session: AsyncSession) -> UnitOfWork:
        return SqlAlchemyUnitOfWork(session)

    @provide(scope=Scope.REQUEST)
    def user_query_service(self, session: AsyncSession) -> UserQueryService:
        return SqlAlchemyUserQueryService(session)
