# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Event-dispatching provider.

Handler registration lives here, in the composition root — adding a new
subscriber is one line, next to all the other wiring.
"""

from dishka import Provider, Scope, provide

from app.application.shared.interfaces import EventDispatcher
from app.domain.users.events import UserRegistered
from app.infrastructure.messaging.in_process import (
    InProcessEventDispatcher,
    log_user_registered,
)


class EventsProvider(Provider):
    scope = Scope.APP

    @provide
    def event_dispatcher(self) -> EventDispatcher:
        dispatcher = InProcessEventDispatcher()
        dispatcher.register(UserRegistered, log_user_registered)
        return dispatcher
