# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Security providers: clock, password hasher, token service (all process-wide)."""

from dishka import Provider, Scope, provide

from app.application.shared.interfaces import Clock, PasswordHasher, TokenService
from app.core.config import JwtSettings
from app.infrastructure.clock import SystemClock
from app.infrastructure.security.jwt_service import JwtTokenService
from app.infrastructure.security.password_hasher import PwdlibPasswordHasher


class SecurityProvider(Provider):
    scope = Scope.APP

    @provide
    def clock(self) -> Clock:
        return SystemClock()

    @provide
    def password_hasher(self) -> PasswordHasher:
        return PwdlibPasswordHasher()

    @provide
    def token_service(self, settings: JwtSettings, clock: Clock) -> TokenService:
        return JwtTokenService(settings, clock)
