# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Providers for application use-case handlers (request-scoped).

Each handler's constructor dependencies (unit of work, hasher, token service,
read model, clock) are resolved by Dishka from the other providers.
"""

from dishka import Provider, Scope, provide

from app.application.auth.commands.login import LoginHandler
from app.application.auth.commands.logout import LogoutHandler
from app.application.auth.commands.refresh_token import RefreshTokenHandler
from app.application.users.commands.change_password import ChangePasswordHandler
from app.application.users.commands.create_user import CreateUserHandler
from app.application.users.queries.get_user import GetUserHandler
from app.application.users.queries.list_users import ListUsersHandler


class UseCasesProvider(Provider):
    scope = Scope.REQUEST

    change_password = provide(ChangePasswordHandler)
    create_user = provide(CreateUserHandler)
    login = provide(LoginHandler)
    logout = provide(LogoutHandler)
    refresh_token = provide(RefreshTokenHandler)
    get_user = provide(GetUserHandler)
    list_users = provide(ListUsersHandler)
