# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Use case: change the current user's password (write side).

Demonstrates the aggregate update path: load → verify invariant → mutate via
the aggregate's own method → ``repository.update`` → ``commit``.
"""

from dataclasses import dataclass
from uuid import UUID

from app.application.shared.interfaces import PasswordHasher, UnitOfWork
from app.domain.auth.exceptions import InvalidCredentialsError
from app.domain.users.exceptions import UserNotFoundError
from app.domain.users.value_objects import HashedPassword, UserId


@dataclass(frozen=True, slots=True)
class ChangePasswordCommand:
    user_id: UUID
    current_password: str
    new_password: str


class ChangePasswordHandler:
    def __init__(self, uow: UnitOfWork, password_hasher: PasswordHasher) -> None:
        self._uow = uow
        self._hasher = password_hasher

    async def execute(self, command: ChangePasswordCommand) -> None:
        user = await self._uow.users.get_by_id(UserId(command.user_id))
        if user is None:
            raise UserNotFoundError
        if not self._hasher.verify(
            command.current_password, user.hashed_password.value
        ):
            raise InvalidCredentialsError

        user.change_password(HashedPassword(self._hasher.hash(command.new_password)))
        await self._uow.users.update(user)
        await self._uow.commit()
