# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Use case: create a user (write side)."""

from dataclasses import dataclass

from app.application.shared.interfaces import Clock, PasswordHasher, UnitOfWork
from app.application.users.dto import UserView
from app.domain.users.entities import User
from app.domain.users.exceptions import EmailAlreadyExistsError
from app.domain.users.value_objects import Email, HashedPassword, UserId


@dataclass(frozen=True, slots=True)
class CreateUserCommand:
    email: str
    password: str


class CreateUserHandler:
    """Validates input, enforces email uniqueness, and persists a new user."""

    def __init__(
        self,
        uow: UnitOfWork,
        password_hasher: PasswordHasher,
        clock: Clock,
    ) -> None:
        self._uow = uow
        self._hasher = password_hasher
        self._clock = clock

    async def execute(self, command: CreateUserCommand) -> UserView:
        email = Email(command.email)

        if await self._uow.users.exists_by_email(email):
            raise EmailAlreadyExistsError

        user = User.create(
            user_id=UserId.new(),
            email=email,
            hashed_password=HashedPassword(self._hasher.hash(command.password)),
            created_at=self._clock.now(),
        )
        await self._uow.users.add(user)
        await self._uow.commit()

        return UserView(
            id=user.id.value,
            email=str(user.email),
            is_active=user.is_active,
            created_at=user.created_at,
        )
