# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""OpenTelemetry wiring: traces and metrics over OTLP/HTTP.

Imported lazily from ``create_app`` only when ``OBSERVABILITY__ENABLED=true``,
so the base install works without the optional dependency group. Install it
with ``uv sync --group observability``.

Log/trace correlation: ``trace_context_processor`` is added to the structlog
chain (see app/core/logging.py) and stamps ``trace_id``/``span_id`` on every
event emitted inside a span.
"""

from fastapi import FastAPI
from opentelemetry import metrics, trace
from opentelemetry.exporter.otlp.proto.http.metric_exporter import (
    OTLPMetricExporter,
)
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.instrumentation.asyncpg import AsyncPGInstrumentor
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.instrumentation.sqlalchemy import SQLAlchemyInstrumentor
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from structlog.types import EventDict, WrappedLogger

from app.core.config import Settings


def configure_telemetry(app: FastAPI, settings: Settings) -> TracerProvider:
    """Installs tracing + metrics for the app, SQLAlchemy, and asyncpg."""
    service_name = settings.observability.service_name or settings.app.name
    resource = Resource.create({"service.name": service_name})
    endpoint = settings.observability.otlp_endpoint.rstrip("/")

    tracer_provider = TracerProvider(resource=resource)
    tracer_provider.add_span_processor(
        BatchSpanProcessor(OTLPSpanExporter(endpoint=f"{endpoint}/v1/traces"))
    )
    trace.set_tracer_provider(tracer_provider)

    meter_provider = MeterProvider(
        resource=resource,
        metric_readers=[
            PeriodicExportingMetricReader(
                OTLPMetricExporter(endpoint=f"{endpoint}/v1/metrics")
            )
        ],
    )
    metrics.set_meter_provider(meter_provider)

    FastAPIInstrumentor.instrument_app(app, tracer_provider=tracer_provider)
    SQLAlchemyInstrumentor().instrument(
        tracer_provider=tracer_provider, enable_commenter=True
    )
    AsyncPGInstrumentor().instrument(tracer_provider=tracer_provider)
    return tracer_provider


def trace_context_processor(
    logger: WrappedLogger, method_name: str, event_dict: EventDict
) -> EventDict:
    """structlog processor: correlate log events with the active span."""
    span_context = trace.get_current_span().get_span_context()
    if span_context.is_valid:
        event_dict["trace_id"] = format(span_context.trace_id, "032x")
        event_dict["span_id"] = format(span_context.span_id, "016x")
    return event_dict
