# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Rate-limiting dependency for public (unauthenticated) endpoints.

Resolves the RateLimiter port from the per-request Dishka container — the
backend (Redis in production, an in-memory double in tests) stays behind the
port, and there is no module-global state.
"""

from dishka import AsyncContainer
from fastapi import HTTPException, Request, status

from app.application.shared.interfaces import RateLimiter
from app.core.config import RateLimitSettings


async def rate_limit_auth(request: Request) -> None:
    """Fixed-window limit per client IP for the auth endpoints."""
    container: AsyncContainer = request.state.dishka_container
    limiter = await container.get(RateLimiter)
    settings = await container.get(RateLimitSettings)

    client_host = request.client.host if request.client else "unknown"
    decision = await limiter.check(
        key=f"{request.url.path}:{client_host}",
        limit=settings.auth_requests,
        window_seconds=settings.auth_window_seconds,
    )
    if not decision.allowed:
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail="Too many requests; try again later.",
            headers={"Retry-After": str(decision.retry_after_seconds)},
        )
