# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Argon2 password hashing via pwdlib.

We use a maintained hashing library (pwdlib, Argon2 backend) rather than
hand-rolling anything. Passwords are never stored in plaintext.
"""

from pwdlib import PasswordHash


class PwdlibPasswordHasher:
    """Implements the PasswordHasher port using pwdlib's recommended (Argon2) hasher."""

    def __init__(self) -> None:
        self._hasher = PasswordHash.recommended()

    def hash(self, plain_password: str) -> str:
        return self._hasher.hash(plain_password)

    def verify(self, plain_password: str, hashed_password: str) -> bool:
        return self._hasher.verify(plain_password, hashed_password)
