# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Integration tests for the Users API and health probes."""

from httpx import AsyncClient


async def _auth_headers(
    client: AsyncClient, email: str = "admin@example.com"
) -> dict[str, str]:
    await client.post(
        "/api/v1/auth/register", json={"email": email, "password": "supersecret"}
    )
    r = await client.post(
        "/api/v1/auth/login", json={"email": email, "password": "supersecret"}
    )
    return {"Authorization": f"Bearer {r.json()['access_token']}"}


async def test_liveness(client: AsyncClient) -> None:
    r = await client.get("/api/v1/health")
    assert r.status_code == 200
    assert r.json()["status"] == "ok"


async def test_readiness_checks_db(client: AsyncClient) -> None:
    r = await client.get("/api/v1/health/ready")
    assert r.status_code == 200
    assert r.json()["status"] == "ready"


async def test_list_users_requires_auth(client: AsyncClient) -> None:
    r = await client.get("/api/v1/users")
    assert r.status_code == 401  # missing bearer credentials


async def test_list_users_is_cursor_paginated(client: AsyncClient) -> None:
    headers = await _auth_headers(client)
    for i in range(3):
        r = await client.post(
            "/api/v1/users",
            headers=headers,
            json={"email": f"u{i}@example.com", "password": "supersecret"},
        )
        assert r.status_code == 201, r.text

    # 4 users total (admin + 3); page size 2 should yield a next_cursor.
    r = await client.get("/api/v1/users?limit=2", headers=headers)
    assert r.status_code == 200, r.text
    body = r.json()
    assert len(body["items"]) == 2
    assert body["next_cursor"] is not None

    # Following the cursor returns the remaining users.
    r = await client.get(
        f"/api/v1/users?limit=2&cursor={body['next_cursor']}", headers=headers
    )
    assert r.status_code == 200, r.text
    assert len(r.json()["items"]) == 2
