# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Every error path must emit RFC 9457 application/problem+json."""

import logging
from uuid import uuid4

import pytest
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient

from app.core.constants import REQUEST_ID_HEADER

PROBLEM_MEDIA_TYPE = "application/problem+json"


def _assert_problem_shape(body: dict[str, object], status_code: int) -> None:
    assert body["status"] == status_code
    assert isinstance(body["title"], str)
    assert isinstance(body["type"], str)


async def test_missing_token_is_problem_json_with_www_authenticate(
    client: AsyncClient,
) -> None:
    r = await client.get("/api/v1/users/me")
    assert r.status_code == 401
    assert r.headers["content-type"].startswith(PROBLEM_MEDIA_TYPE)
    assert r.headers["www-authenticate"] == "Bearer"
    _assert_problem_shape(r.json(), 401)


async def test_unknown_user_is_problem_json_404(
    client: AsyncClient, auth_headers: dict[str, str]
) -> None:
    r = await client.get(f"/api/v1/users/{uuid4()}", headers=auth_headers)
    assert r.status_code == 404
    assert r.headers["content-type"].startswith(PROBLEM_MEDIA_TYPE)
    _assert_problem_shape(r.json(), 404)


async def test_duplicate_email_is_problem_json_409(client: AsyncClient) -> None:
    payload = {"email": "dup-contract@example.com", "password": "supersecret"}
    assert (await client.post("/api/v1/auth/register", json=payload)).status_code == 201
    r = await client.post("/api/v1/auth/register", json=payload)
    assert r.status_code == 409
    assert r.headers["content-type"].startswith(PROBLEM_MEDIA_TYPE)
    _assert_problem_shape(r.json(), 409)


async def test_request_validation_is_problem_json_422_with_errors(
    client: AsyncClient,
) -> None:
    r = await client.post(
        "/api/v1/auth/register",
        json={"email": "not-an-email", "password": "supersecret"},
    )
    assert r.status_code == 422
    assert r.headers["content-type"].startswith(PROBLEM_MEDIA_TYPE)
    body = r.json()
    _assert_problem_shape(body, 422)
    assert body["errors"], "expected at least one validation issue"
    first_issue: dict[str, str] = body["errors"][0]
    assert {"loc", "msg", "type"} <= first_issue.keys()


async def test_unhandled_exception_is_problem_json_500(app: FastAPI) -> None:
    async def boom() -> None:
        raise RuntimeError("intentional test failure")

    app.add_api_route("/boom", boom)

    transport = ASGITransport(app=app, raise_app_exceptions=False)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        r = await client.get("/boom")

    assert r.status_code == 500
    assert r.headers["content-type"].startswith(PROBLEM_MEDIA_TYPE)
    body = r.json()
    _assert_problem_shape(body, 500)
    # No internals leak into the response body.
    assert "intentional test failure" not in r.text
    # The correlation header is present even on the catch-all path.
    assert r.headers.get(REQUEST_ID_HEADER)


async def test_valid_inbound_request_id_is_echoed(client: AsyncClient) -> None:
    r = await client.get("/api/v1/health", headers={REQUEST_ID_HEADER: "trace-42"})
    assert r.headers[REQUEST_ID_HEADER] == "trace-42"


async def test_invalid_inbound_request_id_is_replaced(client: AsyncClient) -> None:
    hostile = "x" * 100 + "\n{}"
    r = await client.get("/api/v1/health", headers={REQUEST_ID_HEADER: hostile})
    echoed = r.headers[REQUEST_ID_HEADER]
    assert echoed != hostile
    assert len(echoed) == 36  # replacement is a generated UUID


async def test_access_log_event_carries_request_id(
    client: AsyncClient, caplog: pytest.LogCaptureFixture
) -> None:
    # The structlog→stdlib bridge makes access events visible to caplog.
    with caplog.at_level(logging.INFO, logger="app.api.middleware"):
        await client.get("/api/v1/health", headers={REQUEST_ID_HEADER: "log-test"})
    messages = [
        record.getMessage()
        for record in caplog.records
        if record.name == "app.api.middleware"
    ]
    assert any(
        "http.request" in message and "log-test" in message for message in messages
    )
