# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Integration tests for the Auth API."""

from httpx import AsyncClient


async def test_register_login_and_me(client: AsyncClient) -> None:
    r = await client.post(
        "/api/v1/auth/register",
        json={"email": "user@example.com", "password": "supersecret"},
    )
    assert r.status_code == 201, r.text
    assert r.json()["email"] == "user@example.com"

    r = await client.post(
        "/api/v1/auth/login",
        json={"email": "user@example.com", "password": "supersecret"},
    )
    assert r.status_code == 200, r.text
    access = r.json()["access_token"]

    r = await client.get(
        "/api/v1/users/me", headers={"Authorization": f"Bearer {access}"}
    )
    assert r.status_code == 200, r.text
    assert r.json()["email"] == "user@example.com"


async def test_login_with_wrong_password_is_401(client: AsyncClient) -> None:
    await client.post(
        "/api/v1/auth/register",
        json={"email": "x@example.com", "password": "supersecret"},
    )
    r = await client.post(
        "/api/v1/auth/login",
        json={"email": "x@example.com", "password": "wrong-password"},
    )
    assert r.status_code == 401


async def test_duplicate_registration_is_409(client: AsyncClient) -> None:
    payload = {"email": "dup@example.com", "password": "supersecret"}
    assert (await client.post("/api/v1/auth/register", json=payload)).status_code == 201
    r = await client.post("/api/v1/auth/register", json=payload)
    assert r.status_code == 409


async def test_refresh_returns_new_tokens(client: AsyncClient) -> None:
    await client.post(
        "/api/v1/auth/register",
        json={"email": "r@example.com", "password": "supersecret"},
    )
    r = await client.post(
        "/api/v1/auth/login",
        json={"email": "r@example.com", "password": "supersecret"},
    )
    refresh = r.json()["refresh_token"]
    r = await client.post("/api/v1/auth/refresh", json={"refresh_token": refresh})
    assert r.status_code == 200, r.text
    assert "access_token" in r.json()
