# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Refresh-token rotation, reuse detection, logout, and revocation."""

from httpx import AsyncClient

CREDENTIALS = {"email": "rotator@example.com", "password": "supersecret"}


async def _login(client: AsyncClient) -> dict[str, str]:
    await client.post("/api/v1/auth/register", json=CREDENTIALS)
    r = await client.post("/api/v1/auth/login", json=CREDENTIALS)
    assert r.status_code == 200, r.text
    body: dict[str, str] = r.json()
    return body


async def test_refresh_rotates_and_replay_kills_the_family(
    client: AsyncClient,
) -> None:
    tokens = await _login(client)
    old_refresh = tokens["refresh_token"]

    r = await client.post("/api/v1/auth/refresh", json={"refresh_token": old_refresh})
    assert r.status_code == 200, r.text
    new_refresh = r.json()["refresh_token"]
    assert new_refresh != old_refresh

    # Replaying the rotated (revoked) token is treated as theft…
    r = await client.post("/api/v1/auth/refresh", json={"refresh_token": old_refresh})
    assert r.status_code == 401
    assert r.headers["content-type"].startswith("application/problem+json")

    # …and the whole family dies with it, including the fresh successor.
    r = await client.post("/api/v1/auth/refresh", json={"refresh_token": new_refresh})
    assert r.status_code == 401


async def test_logout_revokes_the_session_family(client: AsyncClient) -> None:
    tokens = await _login(client)

    r = await client.post(
        "/api/v1/auth/logout", json={"refresh_token": tokens["refresh_token"]}
    )
    assert r.status_code == 204, r.text

    r = await client.post(
        "/api/v1/auth/refresh", json={"refresh_token": tokens["refresh_token"]}
    )
    assert r.status_code == 401


async def test_password_change_revokes_all_refresh_tokens(
    client: AsyncClient,
) -> None:
    tokens = await _login(client)

    r = await client.put(
        "/api/v1/users/me/password",
        headers={"Authorization": f"Bearer {tokens['access_token']}"},
        json={
            "current_password": CREDENTIALS["password"],
            "new_password": "brand-new-pass-1",
        },
    )
    assert r.status_code == 204, r.text

    r = await client.post(
        "/api/v1/auth/refresh", json={"refresh_token": tokens["refresh_token"]}
    )
    assert r.status_code == 401


async def test_access_token_cannot_be_used_as_refresh(client: AsyncClient) -> None:
    tokens = await _login(client)
    r = await client.post(
        "/api/v1/auth/refresh", json={"refresh_token": tokens["access_token"]}
    )
    assert r.status_code == 401


async def test_logout_is_idempotent_for_unknown_but_valid_token(
    client: AsyncClient,
) -> None:
    tokens = await _login(client)
    body = {"refresh_token": tokens["refresh_token"]}
    assert (await client.post("/api/v1/auth/logout", json=body)).status_code == 204
    # Second logout with the same (now family-revoked) token still succeeds.
    assert (await client.post("/api/v1/auth/logout", json=body)).status_code == 204


async def test_garbage_refresh_token_is_401(client: AsyncClient) -> None:
    r = await client.post("/api/v1/auth/refresh", json={"refresh_token": "not-a-jwt"})
    assert r.status_code == 401
