# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Security middleware: headers, host allow-list, body-size cap."""

from httpx import ASGITransport, AsyncClient

from tests.conftest import build_test_app, make_test_settings


async def test_security_headers_are_present(client: AsyncClient) -> None:
    r = await client.get("/api/v1/health")
    assert r.headers["x-content-type-options"] == "nosniff"
    assert r.headers["x-frame-options"] == "DENY"
    assert r.headers["referrer-policy"] == "no-referrer"
    assert "permissions-policy" in r.headers
    # HSTS is production-only; the test environment must not set it.
    assert "strict-transport-security" not in r.headers


async def test_untrusted_host_is_rejected() -> None:
    app = await build_test_app(make_test_settings(allowed_hosts=["good.example"]))
    try:
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as client:
            allowed = await client.get(
                "/api/v1/health", headers={"Host": "good.example"}
            )
            assert allowed.status_code == 200

            rejected = await client.get(
                "/api/v1/health", headers={"Host": "evil.example"}
            )
            assert rejected.status_code == 400
    finally:
        await app.state.dishka_container.close()


async def test_oversized_body_is_413_problem_json(client: AsyncClient) -> None:
    # Default cap is 1 MiB; send a bit more than that.
    huge = "x" * (1_048_576 + 100)
    r = await client.post(
        "/api/v1/auth/register",
        json={"email": "big@example.com", "password": huge},
    )
    assert r.status_code == 413
    assert r.headers["content-type"].startswith("application/problem+json")
    assert r.json()["status"] == 413
