# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Public auth endpoints are rate-limited per client."""

from httpx import ASGITransport, AsyncClient

from tests.conftest import build_test_app, make_test_settings


async def test_login_flood_gets_429_with_retry_after() -> None:
    app = await build_test_app(make_test_settings(auth_rate_limit_requests=2))
    try:
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as client:
            payload = {"email": "nobody@example.com", "password": "whatever-123"}
            for _ in range(2):
                r = await client.post("/api/v1/auth/login", json=payload)
                assert r.status_code == 401  # wrong creds, but not limited yet

            r = await client.post("/api/v1/auth/login", json=payload)
            assert r.status_code == 429
            assert r.headers["content-type"].startswith("application/problem+json")
            assert int(r.headers["retry-after"]) >= 1
            assert r.json()["status"] == 429
    finally:
        await app.state.dishka_container.close()


async def test_register_and_login_have_separate_buckets() -> None:
    app = await build_test_app(make_test_settings(auth_rate_limit_requests=2))
    try:
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as client:
            payload = {"email": "bucket@example.com", "password": "supersecret"}
            for _ in range(2):
                await client.post("/api/v1/auth/login", json=payload)
            # Login is exhausted; register must still be allowed.
            r = await client.post("/api/v1/auth/register", json=payload)
            assert r.status_code == 201, r.text
    finally:
        await app.state.dishka_container.close()
