# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""The aggregate update path: change password end to end."""

from dishka import AsyncContainer
from fastapi import FastAPI
from httpx import AsyncClient

from app.application.shared.interfaces import Clock, UnitOfWork
from app.domain.users.entities import User
from app.domain.users.exceptions import EmailAlreadyExistsError
from app.domain.users.value_objects import Email, HashedPassword, UserId

CREDENTIALS = {"email": "changer@example.com", "password": "old-password-1"}


async def _register_and_login(client: AsyncClient) -> dict[str, str]:
    await client.post("/api/v1/auth/register", json=CREDENTIALS)
    r = await client.post("/api/v1/auth/login", json=CREDENTIALS)
    return {"Authorization": f"Bearer {r.json()['access_token']}"}


async def test_change_password_persists_and_old_password_stops_working(
    client: AsyncClient,
) -> None:
    headers = await _register_and_login(client)

    r = await client.put(
        "/api/v1/users/me/password",
        headers=headers,
        json={
            "current_password": CREDENTIALS["password"],
            "new_password": "new-password-2",
        },
    )
    assert r.status_code == 204, r.text

    r = await client.post("/api/v1/auth/login", json=CREDENTIALS)
    assert r.status_code == 401

    r = await client.post(
        "/api/v1/auth/login",
        json={"email": CREDENTIALS["email"], "password": "new-password-2"},
    )
    assert r.status_code == 200, r.text


async def test_change_password_with_wrong_current_password_is_401(
    client: AsyncClient,
) -> None:
    headers = await _register_and_login(client)
    r = await client.put(
        "/api/v1/users/me/password",
        headers=headers,
        json={"current_password": "not-the-password", "new_password": "irrelevant-9"},
    )
    assert r.status_code == 401
    assert r.headers["content-type"].startswith("application/problem+json")


async def test_commit_translates_email_unique_violation(
    app: FastAPI, client: AsyncClient
) -> None:
    """The constraint, not the pre-check, is the uniqueness source of truth."""
    await client.post("/api/v1/auth/register", json=CREDENTIALS)

    container: AsyncContainer = app.state.dishka_container
    async with container() as request_scope:
        uow = await request_scope.get(UnitOfWork)
        clock = await request_scope.get(Clock)
        duplicate = User.create(
            user_id=UserId.new(),
            email=Email(CREDENTIALS["email"]),
            hashed_password=HashedPassword("x" * 32),
            created_at=clock.now(),
        )
        # Bypass the exists_by_email fast path, as a concurrent request would.
        await uow.users.add(duplicate)
        try:
            await uow.commit()
            raise AssertionError("expected EmailAlreadyExistsError")
        except EmailAlreadyExistsError:
            pass
