# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""In-memory test doubles for the application's ports.

Every fake satisfies its Protocol structurally — no inheritance needed. Use
them to unit-test handlers without I/O, and (via Dishka provider overrides)
to keep integration tests free of external services.
"""

import time

from dishka import Provider, Scope, provide

from app.application.shared.interfaces import RateLimitDecision, RateLimiter


class InMemoryAdaptersProvider(Provider):
    """Replaces adapters that need external services with in-memory doubles.

    Passed to ``create_app(extra_providers=...)``; ``override=True`` makes
    these bindings win over the defaults — the documented recipe for swapping
    any port in tests.
    """

    scope = Scope.APP

    @provide(override=True)
    def rate_limiter(self) -> RateLimiter:
        return InMemoryRateLimiter()


class InMemoryRateLimiter:
    """Fixed-window rate limiter backed by a plain dict (single-process)."""

    def __init__(self) -> None:
        self._windows: dict[str, tuple[float, int]] = {}

    async def check(
        self, key: str, limit: int, window_seconds: int
    ) -> RateLimitDecision:
        now = time.monotonic()
        window_start, count = self._windows.get(key, (now, 0))
        if now - window_start >= window_seconds:
            window_start, count = now, 0
        count += 1
        self._windows[key] = (window_start, count)
        if count > limit:
            remaining = window_seconds - (now - window_start)
            return RateLimitDecision(
                allowed=False, retry_after_seconds=max(1, round(remaining))
            )
        return RateLimitDecision(allowed=True, retry_after_seconds=0)
