# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Base type for domain events recorded by aggregates."""

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class DomainEvent:
    """Marker base class for domain events.

    Concrete events subclass this with their own (typed) fields. Aggregates
    collect them via ``AggregateRoot.record_event`` and the application layer
    dispatches them after a successful commit.
    """
