# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Base domain exceptions.

The domain layer owns its error vocabulary and knows nothing about HTTP or any
framework. The presentation layer is responsible for translating these into
transport-specific responses (see ``app/api/exception_handlers.py``).
"""


class DomainError(Exception):
    """Base class for all domain-level errors.

    ``message`` is human-readable and safe to surface to API clients.
    """

    message: str = "A domain error occurred."

    def __init__(self, message: str | None = None) -> None:
        if message is not None:
            self.message = message
        super().__init__(self.message)


class ValidationError(DomainError):
    """Raised when a value object or entity invariant is violated."""

    message = "Validation failed."
