# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""SQLAlchemy unit of work."""

from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.users.repositories import UserRepository
from app.infrastructure.database.repositories.user_repository import (
    SqlAlchemyUserRepository,
)


class SqlAlchemyUnitOfWork:
    """Wraps a single AsyncSession and exposes the aggregate repositories.

    The session's lifecycle — and therefore rollback-on-error — is owned by the
    DI container, which yields one session per request and closes it at the end
    (an uncommitted session rolls back on close). This class only decides *when*
    to commit.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session
        self.users: UserRepository = SqlAlchemyUserRepository(session)

    async def commit(self) -> None:
        await self._session.commit()

    async def rollback(self) -> None:
        await self._session.rollback()
