# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Server-side state for issued refresh tokens.

Each refresh token is persisted by its ``jti`` claim and belongs to a
*family*: the chain of tokens produced by rotating one original login.
Revoking the family invalidates every descendant at once — the primitive
behind logout, reuse detection, and password-change revocation.
"""

from dataclasses import dataclass
from datetime import datetime
from uuid import UUID

from app.domain.users.value_objects import UserId


@dataclass
class RefreshTokenRecord:
    jti: UUID
    user_id: UserId
    family_id: UUID
    expires_at: datetime
    revoked_at: datetime | None = None

    @property
    def is_revoked(self) -> bool:
        return self.revoked_at is not None

    def revoke(self, at: datetime) -> None:
        if self.revoked_at is None:
            self.revoked_at = at
