# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Authentication domain exceptions."""

from app.domain.shared.exceptions import DomainError


class InvalidCredentialsError(DomainError):
    message = "Invalid email or password."


class InvalidTokenError(DomainError):
    message = "Invalid or expired token."
