# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Authentication domain exceptions."""

from app.domain.shared.exceptions import DomainError


class InvalidCredentialsError(DomainError):
    message = "Invalid email or password."


class InvalidTokenError(DomainError):
    message = "Invalid token."


class TokenExpiredError(InvalidTokenError):
    """Distinct from invalid: the client should refresh or re-authenticate."""

    message = "Token has expired."
