# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Repository port for refresh-token records.

Declared in the domain layer, implemented in infrastructure, exposed on the
UnitOfWork so rotation and revocation share the caller's transaction.
"""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.auth.entities import RefreshTokenRecord
from app.domain.users.value_objects import UserId


class RefreshTokenRepository(Protocol):
    async def add(self, record: RefreshTokenRecord) -> None: ...

    async def update(self, record: RefreshTokenRecord) -> None: ...

    async def get_by_jti(self, jti: UUID) -> RefreshTokenRecord | None: ...

    async def revoke_family(self, family_id: UUID, at: datetime) -> None: ...

    async def revoke_all_for_user(self, user_id: UserId, at: datetime) -> None: ...
