# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Seed the database with a demo user.

Doubles as the canonical example of driving the Dishka container outside an
HTTP request (the same pattern a worker or CLI command uses): build settings,
create the container, enter a nested scope, resolve a handler, close cleanly.

Run with: make seed  (or: uv run python -m scripts.seed)
"""

import asyncio

import structlog

from app.application.users.commands.create_user import (
    CreateUserCommand,
    CreateUserHandler,
)
from app.core.config import get_settings
from app.core.logging import configure_logging
from app.domain.users.exceptions import EmailAlreadyExistsError
from app.ioc.container import create_container

DEMO_EMAIL = "demo@example.com"
DEMO_PASSWORD = "demo-password-change-me"  # local demo credential, not a secret

logger = structlog.get_logger()


async def seed() -> None:
    settings = get_settings()
    configure_logging(settings)
    container = create_container(settings)
    try:
        async with container() as request_scope:
            handler = await request_scope.get(CreateUserHandler)
            try:
                view = await handler.execute(
                    CreateUserCommand(email=DEMO_EMAIL, password=DEMO_PASSWORD)
                )
                logger.info("seed.user_created", user_id=str(view.id), email=view.email)
            except EmailAlreadyExistsError:
                logger.info("seed.user_exists", email=DEMO_EMAIL)
    finally:
        await container.close()


if __name__ == "__main__":
    asyncio.run(seed())
