# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""SQLAlchemy implementation of the RefreshTokenRepository port."""

from datetime import datetime
from uuid import UUID

from sqlalchemy import update
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.auth.entities import RefreshTokenRecord
from app.domain.auth.exceptions import InvalidTokenError
from app.domain.users.value_objects import UserId
from app.infrastructure.database.mappers.refresh_token_mapper import (
    apply_to_model,
    to_domain,
    to_model,
)
from app.infrastructure.database.models.refresh_token import RefreshTokenModel


class SqlAlchemyRefreshTokenRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def add(self, record: RefreshTokenRecord) -> None:
        self._session.add(to_model(record))

    async def update(self, record: RefreshTokenRecord) -> None:
        model = await self._session.get(RefreshTokenModel, record.jti)
        if model is None:
            raise InvalidTokenError
        apply_to_model(record, model)

    async def get_by_jti(self, jti: UUID) -> RefreshTokenRecord | None:
        model = await self._session.get(RefreshTokenModel, jti)
        return to_domain(model) if model is not None else None

    async def revoke_family(self, family_id: UUID, at: datetime) -> None:
        # One bulk UPDATE revokes every live token in the family.
        await self._session.execute(
            update(RefreshTokenModel)
            .where(
                RefreshTokenModel.family_id == family_id,
                RefreshTokenModel.revoked_at.is_(None),
            )
            .values(revoked_at=at)
        )

    async def revoke_all_for_user(self, user_id: UserId, at: datetime) -> None:
        await self._session.execute(
            update(RefreshTokenModel)
            .where(
                RefreshTokenModel.user_id == user_id.value,
                RefreshTokenModel.revoked_at.is_(None),
            )
            .values(revoked_at=at)
        )
