# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""SQLAlchemy implementation of the UserRepository port (write side)."""

from sqlalchemy import exists, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.users.entities import User
from app.domain.users.exceptions import UserNotFoundError
from app.domain.users.value_objects import Email, UserId
from app.infrastructure.database.mappers.user_mapper import (
    apply_to_model,
    to_domain,
    to_model,
)
from app.infrastructure.database.models.user import UserModel


class SqlAlchemyUserRepository:
    """Loads and persists User aggregates via an AsyncSession.

    Writes are added to the session here; the unit of work decides when to
    commit, keeping transaction control in one place.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def add(self, user: User) -> None:
        self._session.add(to_model(user))

    async def update(self, user: User) -> None:
        # ``session.get`` returns the tracked instance (or fetches it), so the
        # copied fields are flushed as an UPDATE on commit.
        model = await self._session.get(UserModel, user.id.value)
        if model is None:
            raise UserNotFoundError
        apply_to_model(user, model)

    async def get_by_id(self, user_id: UserId) -> User | None:
        model = await self._session.get(UserModel, user_id.value)
        return to_domain(model) if model is not None else None

    async def get_by_email(self, email: Email) -> User | None:
        result = await self._session.execute(
            select(UserModel).where(UserModel.email == str(email))
        )
        model = result.scalar_one_or_none()
        return to_domain(model) if model is not None else None

    async def exists_by_email(self, email: Email) -> bool:
        result = await self._session.execute(
            select(exists().where(UserModel.email == str(email)))
        )
        return bool(result.scalar())
