# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Postgres test tier: real database, real migration chain.

Requires Docker (testcontainers spins up postgres:17). Deselected by default —
run with `make test-pg` (pytest -m pg). One container serves the whole
session; each test gets a fresh app and a truncated schema.
"""

import os
from collections.abc import AsyncIterator, Iterator

import pytest
from alembic import command
from alembic.config import Config
from dishka import AsyncContainer
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine
from testcontainers.community.postgres import PostgresContainer

from app.core.config import get_settings
from tests.conftest import build_test_app, make_test_settings


@pytest.fixture(scope="session")
def pg_url() -> Iterator[str]:
    with PostgresContainer("postgres:17-alpine", driver="asyncpg") as container:
        yield container.get_connection_url()


@pytest.fixture(scope="session")
def migrated_pg_url(pg_url: str) -> str:
    """Applies the real Alembic chain — migrations are executed, not assumed."""
    # migrations/env.py reads the URL via get_settings(); override through the
    # environment and drop the cached instance.
    os.environ["DATABASE__URL"] = pg_url
    get_settings.cache_clear()
    command.upgrade(Config("alembic.ini"), "head")
    return pg_url


@pytest.fixture
async def pg_app(migrated_pg_url: str) -> AsyncIterator[FastAPI]:
    application = await build_test_app(
        make_test_settings(database_url=migrated_pg_url), create_schema=False
    )
    container: AsyncContainer = application.state.dishka_container
    try:
        yield application
    finally:
        engine = await container.get(AsyncEngine)
        async with engine.begin() as conn:
            await conn.execute(text("TRUNCATE TABLE refresh_tokens, users"))
        await container.close()


@pytest.fixture
async def pg_client(pg_app: FastAPI) -> AsyncIterator[AsyncClient]:
    transport = ASGITransport(app=pg_app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        yield client
