# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""What SQLite cannot prove: dialect behaviour, migrations, real constraints."""

import asyncio

import pytest
from fastapi import FastAPI
from httpx import AsyncClient
from sqlalchemy import Connection
from sqlalchemy.ext.asyncio import AsyncEngine

from app.infrastructure.database.models.base import Base

pytestmark = pytest.mark.pg

CREDENTIALS = {"email": "pg-user@example.com", "password": "supersecret"}


async def test_full_auth_flow_on_postgres(pg_client: AsyncClient) -> None:
    r = await pg_client.post("/api/v1/auth/register", json=CREDENTIALS)
    assert r.status_code == 201, r.text

    r = await pg_client.post("/api/v1/auth/login", json=CREDENTIALS)
    assert r.status_code == 200, r.text
    tokens = r.json()

    r = await pg_client.get(
        "/api/v1/users/me",
        headers={"Authorization": f"Bearer {tokens['access_token']}"},
    )
    assert r.status_code == 200, r.text
    assert r.json()["email"] == CREDENTIALS["email"]

    r = await pg_client.post(
        "/api/v1/auth/refresh", json={"refresh_token": tokens["refresh_token"]}
    )
    assert r.status_code == 200, r.text

    # The rotated original must be dead — reuse detection on real Postgres.
    r = await pg_client.post(
        "/api/v1/auth/refresh", json={"refresh_token": tokens["refresh_token"]}
    )
    assert r.status_code == 401


async def test_concurrent_duplicate_registration_is_409_not_500(
    pg_client: AsyncClient,
) -> None:
    """The unique constraint, not the pre-check, must win the race."""

    async def register() -> int:
        r = await pg_client.post("/api/v1/auth/register", json=CREDENTIALS)
        return r.status_code

    statuses = sorted(await asyncio.gather(register(), register()))
    assert statuses == [201, 409]


async def test_no_model_migration_drift(pg_app: FastAPI) -> None:
    """Autogenerate against the migrated schema must produce an empty diff."""
    from alembic.autogenerate import compare_metadata
    from alembic.runtime.migration import MigrationContext

    def compare(sync_conn: Connection) -> list[object]:
        context = MigrationContext.configure(sync_conn, opts={"compare_type": True})
        return list(compare_metadata(context, Base.metadata))

    engine: AsyncEngine = await pg_app.state.dishka_container.get(AsyncEngine)
    async with engine.connect() as conn:
        diffs = await conn.run_sync(compare)
    assert diffs == [], f"model/migration drift detected: {diffs}"
