# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Health and readiness probes."""

from dishka.integrations.fastapi import DishkaRoute, FromDishka
from fastapi import APIRouter
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

router = APIRouter(prefix="/health", tags=["health"], route_class=DishkaRoute)


@router.get("", summary="Liveness probe")
async def liveness() -> dict[str, str]:
    return {"status": "ok"}


@router.get("/ready", summary="Readiness probe")
async def readiness(session: FromDishka[AsyncSession]) -> dict[str, str]:
    # Verifies the process can reach the database before declaring itself ready.
    await session.execute(text("SELECT 1"))
    return {"status": "ready"}
