# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Read-side DTOs for the Users domain."""

from dataclasses import dataclass
from datetime import datetime
from uuid import UUID


@dataclass(frozen=True, slots=True)
class UserView:
    """A flat, read-optimised projection of a user. Holds no domain behaviour."""

    id: UUID
    email: str
    is_active: bool
    created_at: datetime
