# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Read-side port for the Users domain (CQRS query side).

Reads bypass the aggregate: implementations may query straight into DTOs (e.g.
via SQLAlchemy Core), avoiding the cost of rehydrating domain objects.
"""

from typing import Protocol
from uuid import UUID

from app.application.shared.dto import Page
from app.application.users.dto import UserView


class UserQueryService(Protocol):
    async def get_by_id(self, user_id: UUID) -> UserView | None: ...

    async def list(self, *, limit: int, cursor: str | None) -> Page[UserView]: ...
