# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Log/trace correlation processor.

Uses a locally constructed TracerProvider on purpose: setting the global
provider or instrumenting the app would leak process-global state into the
rest of the suite.
"""

from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.trace import use_span
from structlog.types import EventDict

from app.core.telemetry import trace_context_processor


def _run_processor() -> EventDict:
    return trace_context_processor(None, "info", {"event": "test"})


def test_outside_a_span_adds_nothing() -> None:
    event = _run_processor()
    assert "trace_id" not in event
    assert "span_id" not in event


def test_inside_a_span_adds_trace_and_span_ids() -> None:
    tracer = TracerProvider().get_tracer("test")
    with use_span(tracer.start_span("op"), end_on_exit=True):
        event = _run_processor()
    assert len(event["trace_id"]) == 32
    assert len(event["span_id"]) == 16
