# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Domain events: recording on the aggregate and typed in-process dispatch."""

from datetime import UTC, datetime

from app.domain.shared.events import DomainEvent
from app.domain.users.entities import User
from app.domain.users.events import UserRegistered
from app.domain.users.value_objects import Email, HashedPassword, UserId
from app.infrastructure.messaging.in_process import InProcessEventDispatcher

NOW = datetime(2026, 1, 1, tzinfo=UTC)


def _make_user() -> User:
    return User.create(
        user_id=UserId.new(),
        email=Email("events@example.com"),
        hashed_password=HashedPassword("hashed"),
        created_at=NOW,
    )


def test_user_create_records_registered_event() -> None:
    user = _make_user()
    events = user.pull_events()
    assert len(events) == 1
    event = events[0]
    assert isinstance(event, UserRegistered)
    assert event.user_id == user.id.value
    assert event.email == "events@example.com"
    assert event.occurred_at == NOW


def test_pull_events_drains_the_aggregate() -> None:
    user = _make_user()
    assert len(user.pull_events()) == 1
    assert user.pull_events() == []


async def test_dispatcher_routes_to_matching_handler_only() -> None:
    received: list[UserRegistered] = []

    async def on_registered(event: UserRegistered) -> None:
        received.append(event)

    dispatcher = InProcessEventDispatcher()
    dispatcher.register(UserRegistered, on_registered)

    class UnrelatedEvent(DomainEvent):
        pass

    event = UserRegistered(user_id=UserId.new().value, email="x@y.dev", occurred_at=NOW)
    await dispatcher.dispatch([event, UnrelatedEvent()])

    assert received == [event]
