# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Unit tests for the Users domain — pure, no I/O, no framework."""

from datetime import UTC, datetime

import pytest

from app.domain.shared.exceptions import ValidationError
from app.domain.users.entities import User
from app.domain.users.value_objects import Email, HashedPassword, UserId


def test_email_is_normalised() -> None:
    assert str(Email("  Foo@Example.COM ")) == "foo@example.com"


def test_invalid_email_raises() -> None:
    with pytest.raises(ValidationError):
        Email("not-an-email")


def test_empty_hashed_password_raises() -> None:
    with pytest.raises(ValidationError):
        HashedPassword("")


def test_user_create_is_active_by_default() -> None:
    user = User.create(
        user_id=UserId.new(),
        email=Email("a@b.com"),
        hashed_password=HashedPassword("x"),
        created_at=datetime.now(UTC),
    )
    assert user.is_active is True


def test_entities_are_equal_by_identity() -> None:
    uid = UserId.new()
    now = datetime.now(UTC)
    a = User.create(
        user_id=uid,
        email=Email("a@b.com"),
        hashed_password=HashedPassword("x"),
        created_at=now,
    )
    b = User.create(
        user_id=uid,
        email=Email("c@d.com"),
        hashed_password=HashedPassword("y"),
        created_at=now,
    )
    assert a == b  # same identity, different attributes
