# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Use case: fetch a single user by id (read side)."""

from dataclasses import dataclass
from uuid import UUID

from app.application.users.dto import UserView
from app.application.users.interfaces import UserQueryService
from app.domain.users.exceptions import UserNotFoundError


@dataclass(frozen=True, slots=True)
class GetUserQuery:
    user_id: UUID


class GetUserHandler:
    def __init__(self, users: UserQueryService) -> None:
        self._users = users

    async def execute(self, query: GetUserQuery) -> UserView:
        view = await self._users.get_by_id(query.user_id)
        if view is None:
            raise UserNotFoundError
        return view
