# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Translation between RefreshTokenRecord and its ORM representation."""

from app.domain.auth.entities import RefreshTokenRecord
from app.domain.users.value_objects import UserId
from app.infrastructure.database.mappers.tz import as_utc
from app.infrastructure.database.models.refresh_token import RefreshTokenModel


def to_domain(model: RefreshTokenModel) -> RefreshTokenRecord:
    return RefreshTokenRecord(
        jti=model.jti,
        user_id=UserId(model.user_id),
        family_id=model.family_id,
        expires_at=as_utc(model.expires_at),
        revoked_at=as_utc(model.revoked_at) if model.revoked_at else None,
    )


def to_model(record: RefreshTokenRecord) -> RefreshTokenModel:
    return RefreshTokenModel(
        jti=record.jti,
        user_id=record.user_id.value,
        family_id=record.family_id,
        expires_at=record.expires_at,
        revoked_at=record.revoked_at,
    )


def apply_to_model(record: RefreshTokenRecord, model: RefreshTokenModel) -> None:
    model.revoked_at = record.revoked_at
