# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Timezone normalisation at the persistence boundary.

Postgres returns tz-aware datetimes for ``DateTime(timezone=True)`` columns;
SQLite (used in the fast test tier) stores and returns naive ones. The domain
works exclusively with aware UTC datetimes, so mappers normalise every value
read from the database.
"""

from datetime import UTC, datetime


def as_utc(value: datetime) -> datetime:
    return value if value.tzinfo is not None else value.replace(tzinfo=UTC)
