# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Translation between the User aggregate and its ORM representation.

Keeping mapping in one place means the domain never imports SQLAlchemy and the
ORM never imports value objects' validation logic at call sites.
"""

from app.domain.users.entities import User
from app.domain.users.value_objects import Email, HashedPassword, UserId
from app.infrastructure.database.mappers.tz import as_utc
from app.infrastructure.database.models.user import UserModel


def to_domain(model: UserModel) -> User:
    return User(
        id=UserId(model.id),
        email=Email(model.email),
        hashed_password=HashedPassword(model.hashed_password),
        is_active=model.is_active,
        created_at=as_utc(model.created_at),
    )


def to_model(user: User) -> UserModel:
    return UserModel(
        id=user.id.value,
        email=str(user.email),
        hashed_password=user.hashed_password.value,
        is_active=user.is_active,
        created_at=user.created_at,
    )


def apply_to_model(user: User, model: UserModel) -> None:
    """Copies the aggregate's state onto a session-tracked model.

    Explicit field-by-field copy (not ``session.merge``) keeps the Data Mapper
    honest: what persists on update is exactly what is listed here.
    """
    model.email = str(user.email)
    model.hashed_password = user.hashed_password.value
    model.is_active = user.is_active
