# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Domain events for the Users aggregate."""

from dataclasses import dataclass
from datetime import datetime
from uuid import UUID

from app.domain.shared.events import DomainEvent


@dataclass(frozen=True, slots=True)
class UserRegistered(DomainEvent):
    user_id: UUID
    email: str
    occurred_at: datetime
