# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""User domain exceptions."""

from app.domain.shared.exceptions import DomainError


class UserNotFoundError(DomainError):
    message = "User not found."


class EmailAlreadyExistsError(DomainError):
    message = "A user with this email already exists."
