# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Repository interface (port) for the User aggregate.

Declared in the domain layer, implemented in infrastructure. The domain depends
on this abstraction — never on a concrete database. We use ``Protocol`` for
structural typing: implementations need not inherit from it.
"""

from typing import Protocol

from app.domain.users.entities import User
from app.domain.users.value_objects import Email, UserId


class UserRepository(Protocol):
    """Persistence boundary for the User aggregate (write side)."""

    async def add(self, user: User) -> None: ...

    async def get_by_id(self, user_id: UserId) -> User | None: ...

    async def get_by_email(self, email: Email) -> User | None: ...

    async def exists_by_email(self, email: Email) -> bool: ...
