# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""The real Argon2 adapter — the one place the actual algorithm is exercised.

Integration tests swap this adapter for StubPasswordHasher (speed), so this
unit test is what keeps the production hashing path honest.
"""

from app.infrastructure.security.password_hasher import PwdlibPasswordHasher


async def test_hash_and_verify_roundtrip() -> None:
    hasher = PwdlibPasswordHasher()
    hashed = await hasher.hash("correct horse battery staple")
    assert hashed != "correct horse battery staple"
    assert hashed.startswith("$argon2")
    assert await hasher.verify("correct horse battery staple", hashed)


async def test_wrong_password_fails_verification() -> None:
    hasher = PwdlibPasswordHasher()
    hashed = await hasher.hash("right-password")
    assert not await hasher.verify("wrong-password", hashed)


async def test_same_password_hashes_differently() -> None:
    hasher = PwdlibPasswordHasher()
    assert await hasher.hash("repeat-me") != await hasher.hash("repeat-me")
