# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""JwtTokenService: claims, expiry, tampering, and type confusion.

PyJWT validates ``exp`` against real wall-clock time, so issuing clocks are
anchored to ``datetime.now`` (shifted into the past to simulate expiry).
"""

from datetime import UTC, datetime, timedelta
from uuid import uuid4

import jwt
import pytest
from pydantic import SecretStr

from app.core.config import JwtSettings
from app.domain.auth.exceptions import InvalidTokenError, TokenExpiredError
from app.infrastructure.security.jwt_service import JwtTokenService
from tests.fakes import FrozenClock

SECRET = "unit-test-secret-0123456789-abcdef"


def _clock_now() -> FrozenClock:
    return FrozenClock(datetime.now(UTC))


def _service(clock: FrozenClock) -> JwtTokenService:
    return JwtTokenService(JwtSettings(secret=SecretStr(SECRET)), clock)


def test_access_token_roundtrip() -> None:
    service = _service(_clock_now())
    token = service.create_access_token("subject-1")
    payload = service.decode(token)
    assert payload.subject == "subject-1"
    assert payload.token_type == "access"


def test_refresh_token_roundtrip_carries_the_given_jti() -> None:
    clock = _clock_now()
    service = _service(clock)
    jti = uuid4()
    issued = service.create_refresh_token("subject-2", jti)
    assert issued.expires_at > clock.now()
    payload = service.decode(issued.token)
    assert payload.token_type == "refresh"
    assert payload.token_id == jti


def test_expired_token_raises_token_expired() -> None:
    # Issued 16 minutes ago with a 15-minute lifetime: already expired.
    stale_clock = FrozenClock(datetime.now(UTC) - timedelta(minutes=16))
    token = _service(stale_clock).create_access_token("subject-3")
    with pytest.raises(TokenExpiredError):
        _service(_clock_now()).decode(token)


def test_tampered_signature_is_invalid() -> None:
    service = _service(_clock_now())
    token = service.create_access_token("subject-4")
    with pytest.raises(InvalidTokenError):
        service.decode(token[:-4] + "AAAA")


def test_garbage_is_invalid() -> None:
    with pytest.raises(InvalidTokenError):
        _service(_clock_now()).decode("not-a-jwt")


def test_token_without_required_claims_is_invalid() -> None:
    clock = _clock_now()
    service = _service(clock)
    # Same secret, but missing jti/iss/aud — must be rejected by `require`.
    bare = jwt.encode(
        {
            "sub": "subject-5",
            "type": "access",
            "iat": int(clock.now().timestamp()),
            "exp": int(clock.now().timestamp()) + 600,
        },
        SECRET,
        algorithm="HS256",
    )
    with pytest.raises(InvalidTokenError):
        service.decode(bare)


def test_wrong_issuer_is_invalid() -> None:
    clock = _clock_now()
    service = _service(clock)
    other = JwtTokenService(
        JwtSettings(secret=SecretStr(SECRET), issuer="someone-else"), clock
    )
    with pytest.raises(InvalidTokenError):
        service.decode(other.create_access_token("subject-6"))
