# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Typed application configuration via pydantic-settings.

Settings come from environment variables (and an optional ``.env`` file).
Nested settings use a double-underscore delimiter, e.g. ``DATABASE__URL``.
Grouping related settings into sub-models keeps the surface organised as the
project grows (``settings.database.url`` rather than a flat ``database_url``).
"""

from enum import StrEnum
from functools import lru_cache

from pydantic import BaseModel, Field, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict


class Environment(StrEnum):
    LOCAL = "local"
    TEST = "test"
    STAGING = "staging"
    PRODUCTION = "production"


class AppSettings(BaseModel):
    name: str = "fastapi-starter"
    debug: bool = False
    cors_origins: list[str] = Field(default_factory=list)


class DatabaseSettings(BaseModel):
    url: str = "postgresql+asyncpg://postgres:postgres@localhost:5432/app"
    echo: bool = False
    pool_size: int = 5
    max_overflow: int = 10


class JwtSettings(BaseModel):
    secret: SecretStr = SecretStr("change-me-in-production")
    algorithm: str = "HS256"
    access_token_expire_minutes: int = 15
    refresh_token_expire_days: int = 30


class RedisSettings(BaseModel):
    url: str = "redis://localhost:6379/0"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        env_nested_delimiter="__",
        extra="ignore",
    )

    environment: Environment = Environment.LOCAL
    app: AppSettings = Field(default_factory=AppSettings)
    database: DatabaseSettings = Field(default_factory=DatabaseSettings)
    jwt: JwtSettings = Field(default_factory=JwtSettings)
    redis: RedisSettings = Field(default_factory=RedisSettings)

    @property
    def is_production(self) -> bool:
        return self.environment is Environment.PRODUCTION


@lru_cache
def get_settings() -> Settings:
    """Cached accessor used as the composition-root entry point."""
    return Settings()
