# Generated by OrchestKit Claude Plugin
# Created: 2026-06-17

"""Structured logging configuration using structlog.

Pretty console output locally; machine-readable JSON everywhere else (for log
aggregation). A request id is bound per request by the middleware.
"""

import logging
import sys

import structlog

from app.core.config import Environment, Settings


def configure_logging(settings: Settings) -> None:
    log_level = logging.DEBUG if settings.app.debug else logging.INFO

    shared_processors: list[structlog.types.Processor] = [
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.TimeStamper(fmt="iso", utc=True),
        structlog.processors.StackInfoRenderer(),
    ]

    renderer: structlog.types.Processor
    if settings.environment is Environment.LOCAL:
        renderer = structlog.dev.ConsoleRenderer()
    else:
        renderer = structlog.processors.JSONRenderer()

    structlog.configure(
        processors=[*shared_processors, renderer],
        wrapper_class=structlog.make_filtering_bound_logger(log_level),
        logger_factory=structlog.PrintLoggerFactory(file=sys.stdout),
        cache_logger_on_first_use=True,
    )
